In [4]:
##changing the working dierc 
import os
os.chdir('P:\SAMPLE DATA')

In [5]:
os.getcwd()

'P:\\SAMPLE DATA'

In [6]:
###importing necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
#import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
#the nlp process will take as long as possible bu try to conplete with in the notice period of this month

In [1]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re

In [9]:
df = pd.read_csv("inbox file.csv")

In [10]:
dataset = pd.read_csv("inbox file.csv")

In [11]:
dataset.drop(['Subject','From: (Name)', 'From: (Address)', 'From: (Type)',
       'To: (Name)', 'To: (Address)', 'To: (Type)', 'CC: (Name)',
       'CC: (Address)', 'CC: (Type)', 'BCC: (Name)', 'BCC: (Address)',
       'BCC: (Type)', 'Billing Information', 'Categories', 'Importance',
       'Mileage', 'Sensitivity'],axis=1,inplace=True)

In [12]:
df=dataset.dropna()

In [13]:
df.isnull().sum()

Body    0
dtype: int64

In [14]:
dataset.dropna(inplace=True)

In [15]:
dataset.head()

Body
0  Good Morning\r\n\r\n \r\n\r\nThe Special tomor...
1  Good Morning\r\n\r\n \r\n\r\nThe soup today is...
2  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...
3  \r\n\r\n\r\n\r\n______________________________...
4  Welcome to the theafgroup.co.uk group.\r\n \t\...

In [22]:
def vader_sentiment_result(sent):
    scores = analyzer.polarity_scores(sent)
    
    if scores['compound'] >= 0.05 :
        return "Positive"
    elif scores['compound'] == 0.05:
        return "Neutral"
    elif scores['compound'] <= - 0.05:
        return "Negative"
    

In [23]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [24]:
dataset["vader_result"] = dataset["Body"].apply(lambda x: vader_sentiment_result(x))

In [25]:
dataset

Body vader_result
0    Good Morning\r\n\r\n \r\n\r\nThe Special tomor...     Positive
1    Good Morning\r\n\r\n \r\n\r\nThe soup today is...     Positive
2    \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...     Negative
3    \r\n\r\n\r\n\r\n______________________________...     Positive
4    Welcome to the theafgroup.co.uk group.\r\n \t\...     Positive
..                                                 ...          ...
591   <https://de-cdn.eyo.net/apps-control-live/ima...         None
592  Good morning everyone, \r\n\r\n \r\n\r\nA whil...     Positive
593  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...     Negative
594   <https://de-cdn.eyo.net/apps-control-live/ima...     Positive
595   <https://de-cdn.eyo.net/apps-control-live/ima...         None

[595 rows x 2 columns]

In [22]:
import tensorflow as tf

In [23]:
def convert_label(inp):
    if inp == "Negative":
        return 1
    elif inp == "Positive":
        return 0

In [24]:
dataset["vader_result"] = dataset["vader_result"].apply(lambda x: convert_label(x))

In [25]:
dataset.dropna(inplace=True)

In [26]:
dataset.head()

Body  vader_result
0  Good Morning\r\n\r\n \r\n\r\nThe Special tomor...           0.0
1  Good Morning\r\n\r\n \r\n\r\nThe soup today is...           0.0
2  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...           1.0
3  \r\n\r\n\r\n\r\n______________________________...           0.0
4  Welcome to the theafgroup.co.uk group.\r\n \t\...           0.0

In [27]:
y=dataset['vader_result']

In [28]:
X=dataset['Body']

In [29]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [30]:
### Vocabulary size
voc_size=5000

In [31]:
y=dataset['vader_result']

In [32]:
y.value_counts()

0.0    420
1.0     93
Name: vader_result, dtype: int64

In [33]:
X=dataset.drop('vader_result',axis=1)

In [34]:
X

Body
0    Good Morning\r\n\r\n \r\n\r\nThe Special tomor...
1    Good Morning\r\n\r\n \r\n\r\nThe soup today is...
2    \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...
3    \r\n\r\n\r\n\r\n______________________________...
4    Welcome to the theafgroup.co.uk group.\r\n \t\...
..                                                 ...
589  Good day everyone,\r\n\r\n \r\n\r\nI’m updatin...
590  \t\r\n <http://cdn.mcauto-images-production.se...
592  Good morning everyone, \r\n\r\n \r\n\r\nA whil...
593  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...
594   <https://de-cdn.eyo.net/apps-control-live/ima...

[513 rows x 1 columns]

In [35]:
messages=X.copy()

In [36]:
messages['Body'][1]

'Good Morning\r\n\r\n \r\n\r\nThe soup today is “Broccoli & Stilton.”\r\n\r\n \r\n\r\nAF Cafe \r\n\r\n \r\n\r\naf.farm <https://af.farm> afinteractive.co.uk <https://afinteractive.co.uk>  \r\nHoningham Thorpe, Colton, Norwich, Norfolk, NR9 5BZ \r\n01603 881881 \r\n\r\n <https://emaildocs.theafgroup.co.uk/email/image003.jpg> \r\n\r\n'

In [37]:
messages.reset_index(inplace=True)

In [38]:
import nltk
import re
from nltk.corpus import stopwords

In [39]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\mohan-
[nltk_data]     prakashj\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [40]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['Body'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [41]:
corpus

['good morn special tomorrow homemad beef burger brioch bun serv salad af cafe af farm http af farm afinteract co uk http afinteract co uk honingham thorp colton norwich norfolk nr bz http emaildoc theafgroup co uk email imag jpg',
 'good morn soup today broccoli stilton af cafe af farm http af farm afinteract co uk http afinteract co uk honingham thorp colton norwich norfolk nr bz http emaildoc theafgroup co uk email imag jpg',
 'icewarp spam report automat gener report inform messag spam folder quarantin e mail account let take administr action click one button next email header note report show first messag sent sender accept messag sender deliv account mohan prakash jeyasankar af farm choos action item account whitelist http mail intouchsystem co uk report html r h f e mohan prakash jeyasankar af farm q deliv http mail intouchsystem co uk report html r h f e mohan prakash jeyasankar af farm q delet http mail intouchsystem co uk report html r h f e mohan prakash jeyasankar af farm q

In [42]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2104,
  965,
  4741,
  2740,
  677,
  4522,
  4269,
  4767,
  3418,
  1006,
  3824,
  4300,
  4068,
  4300,
  661,
  1627,
  4300,
  661,
  2835,
  929,
  4692,
  1627,
  2835,
  929,
  4692,
  766,
  3603,
  1526,
  1061,
  1387,
  3880,
  4100,
  1627,
  1936,
  1811,
  929,
  4692,
  2553,
  3405,
  397],
 [2104,
  965,
  1240,
  997,
  669,
  1682,
  4300,
  4068,
  4300,
  661,
  1627,
  4300,
  661,
  2835,
  929,
  4692,
  1627,
  2835,
  929,
  4692,
  766,
  3603,
  1526,
  1061,
  1387,
  3880,
  4100,
  1627,
  1936,
  1811,
  929,
  4692,
  2553,
  3405,
  397],
 [879,
  2838,
  2580,
  4695,
  4402,
  2580,
  173,
  3803,
  2838,
  1223,
  1117,
  485,
  4140,
  4172,
  2386,
  2194,
  3732,
  1292,
  931,
  2146,
  3012,
  1719,
  2553,
  1378,
  1944,
  2580,
  915,
  1551,
  3803,
  2963,
  3451,
  1439,
  3803,
  3451,
  4144,
  4172,
  2072,
  2205,
  747,
  4300,
  661,
  954,
  1292,
  4138,
  4172,
  4605,
  1627,
  4140,
  3770,
  929,
  4692,
  2580,
  3764,
  

In [43]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4692 1627 2835 ... 2553 3405  397]
 [4692 1627 2835 ... 2553 3405  397]
 [1627 4140 3770 ... 2838 1223 1117]
 ...
 [4692 1627 2835 ... 2553 3405  397]
 [1627 4140 3770 ... 2838 1223 1117]
 [4831 1824 2232 ... 1811  929 4692]]


In [44]:
embedded_docs[0]

array([4692, 1627, 2835,  929, 4692,  766, 3603, 1526, 1061, 1387, 3880,
       4100, 1627, 1936, 1811,  929, 4692, 2553, 3405,  397])

In [45]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [46]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [47]:
len(embedded_docs),y.shape

(513, (513,))

In [48]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [49]:
X_final.shape,y_final.shape

((513, 20), (513,))

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [51]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
6/6 [==============================] - 7s 271ms/step - loss: 0.6672 - accuracy: 0.7813 - val_loss: 0.6218 - val_accuracy: 0.7882
Epoch 2/10
6/6 [==============================] - 0s 35ms/step - loss: 0.5468 - accuracy: 0.8338 - val_loss: 0.4293 - val_accuracy: 0.7882
Epoch 3/10
6/6 [==============================] - 0s 34ms/step - loss: 0.3956 - accuracy: 0.8338 - val_loss: 0.3504 - val_accuracy: 0.7882
Epoch 4/10
6/6 [==============================] - 0s 34ms/step - loss: 0.2691 - accuracy: 0.8630 - val_loss: 0.2522 - val_accuracy: 0.9529
Epoch 5/10
6/6 [==============================] - 0s 35ms/step - loss: 0.1811 - accuracy: 0.9504 - val_loss: 0.1804 - val_accuracy: 0.9647
Epoch 6/10
6/6 [==============================] - 0s 35ms/step - loss: 0.1646 - accuracy: 0.9679 - val_loss: 0.1693 - val_accuracy: 0.9647
Epoch 7/10
6/6 [==============================] - 0s 34ms/step - loss: 0.1530 - accuracy: 0.9708 - val_loss: 0.1563 - val_accuracy: 0.9647
Epoch 8/10
6/6 [==========

In [52]:
y_pred1=model1.predict(X_test)

6/6 [==============================] - 1s 5ms/step


In [53]:
from sklearn.metrics import confusion_matrix

In [54]:
confusion_matrix(y_test,y_pred1.round())

array([[131,   3],
       [  4,  32]], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1.round())

0.9588235294117647

In [56]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1.round()))

              precision    recall  f1-score   support

         0.0       0.97      0.98      0.97       134
         1.0       0.91      0.89      0.90        36

    accuracy                           0.96       170
   macro avg       0.94      0.93      0.94       170
weighted avg       0.96      0.96      0.96       170



In [57]:
from flask import Flask,render_template,url_for,request
import pandas as pd
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
import pickle

In [68]:
dataset.to_csv('nlp1.csv')

In [69]:
df=pd.read_csv('nlp1.csv')

In [67]:
dataset.head()

Body  vader_result
0  Good Morning\r\n\r\n \r\n\r\nThe Special tomor...           0.0
1  Good Morning\r\n\r\n \r\n\r\nThe soup today is...           0.0
2  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...           1.0
3  \r\n\r\n\r\n\r\n______________________________...           0.0
4  Welcome to the theafgroup.co.uk group.\r\n \t\...           0.0

In [70]:
X = df['Body']
y = df['vader_result']

In [71]:
# Extract Feature With CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(X)

In [72]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y,
                                  test_size=0.25, random_state=42)

In [73]:
#Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB

In [74]:
clf = MultinomialNB()
clf.fit(Xtrain,ytrain)
clf.score(Xtest,ytest)

0.9612403100775194

In [75]:
df.head()

Unnamed: 0                                               Body  vader_result
0           0  Good Morning\r\n\r\n \r\n\r\nThe Special tomor...           0.0
1           1  Good Morning\r\n\r\n \r\n\r\nThe soup today is...           0.0
2           2  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...           1.0
3           3  \r\n\r\n\r\n\r\n______________________________...           0.0
4           4  Welcome to the theafgroup.co.uk group.\r\n \t\...           0.0

In [76]:
df['vader_result']

0      0.0
1      0.0
2      1.0
3      0.0
4      0.0
      ... 
508    0.0
509    0.0
510    0.0
511    1.0
512    0.0
Name: vader_result, Length: 513, dtype: float64

In [77]:
df.drop('vader_result',axis=1,inplace=True)

In [82]:
df.head()

Body
0  Good Morning\r\n\r\n \r\n\r\nThe Special tomor...
1  Good Morning\r\n\r\n \r\n\r\nThe soup today is...
2  \r\nIceWarp Spam Report\r\n\r\n\r\nThis automa...
3  \r\n\r\n\r\n\r\n______________________________...
4  Welcome to the theafgroup.co.uk group.\r\n \t\...

In [79]:
df.reset_index(inplace=True)

In [81]:
df.drop(['index','Unnamed: 0'],axis=1,inplace=True)

In [126]:
# Function to Clean the Tweet.
def clean_tweet(tweet):
    return ' '.join(re.sub('(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)|([RT])', ' ', tweet.lower()).split())

In [127]:
# Funciton to analyze Sentiment
def analyze_sentiment(tweet):
    analysis = TextBlob(tweet)
    if analysis.sentiment.polarity > 0:
        return 'Positive'
    elif analysis.sentiment.polarity == 0:
        return 'Neutral'
    else:
        return 'Negative'

In [51]:
def myfunc(n):
  return lambda a : a * n

myfunc(2)

<function __main__.myfunc.<locals>.<lambda>(a)>

In [128]:
def prepCloud(Topic_text,Topic):
    Topic = str(Topic).lower()
    Topic=' '.join(re.sub('([^0-9A-Za-z \t])', ' ', Topic).split())
    Topic = re.split("\s+",str(Topic))
    stopwords = set(STOPWORDS)
    stopwords.update(Topic) ### Add our topic in Stopwords, so it doesnt appear in wordClous###
    text_new = " ".join([txt for txt in Topic_text.split() if txt not in stopwords])
    return text_new

In [48]:
i = 1
while i < 6:
  print(i)
  if i == 3:
    break
  i += 1

1
2
3


In [41]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

1
2
4
5
6


In [46]:
i=1
while i<10:
    print(i)
    if i ==10:
        break
    i+=1

1
2
3
4
5
6
7
8
9


In [129]:
 df['Body'] = df['Body'].apply(lambda x : clean_tweet(x))

In [130]:
df.head()

Body
0  good morning the special tomorrow is homemade ...
1  good morning the soup today is broccoli stilto...
2  icewarp spam report this automatically generat...
3  microsoft teams meeting join on your computer ...
4  welcome to the theafgroup co uk group theafgro...

In [131]:
import textblob
from textblob import TextBlob
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

In [109]:
!pip install wordcloud

  Using cached wordcloud-1.8.2.2-cp39-cp39-win_amd64.whl (153 kB)


In [132]:
df["sentiment"] = df["Body"].apply(lambda x : analyze_sentiment(x))

In [37]:
var=50

In [38]:
if var in range(10,60):print("is in range")

is in range


In [133]:
df.head()

Body sentiment
0  good morning the special tomorrow is homemade ...  Positive
1  good morning the soup today is broccoli stilto...  Positive
2  icewarp spam report this automatically generat...  Negative
3  microsoft teams meeting join on your computer ...  Positive
4  welcome to the theafgroup co uk group theafgro...  Positive

In [134]:
df['sentiment'].unique()

array(['Positive', 'Negative', 'Neutral'], dtype=object)

In [135]:
df.to_csv('clean.csv')